/*
	MIT License
    Copyright (c) 2025 Ajaykrishnan R	
*/

namespace Aviyal;

public enum COMMAND
{
	FOCUS_NEXT_WORKSPACE,
	FOCUS_PREVIOUS_WORKSPACE,
	CLOSE_FOCUSED_WINDOW,
	FOCUS_RIGHT_WINDOW,
	FOCUS_TOP_WINDOW,
	FOCUS_LEFT_WINDOW,
	FOCUS_BOTTOM_WINDOW,

	SHIFT_FOCUSED_WINDOW_RIGHT,
	SHIFT_FOCUSED_WINDOW_LEFT,

	SHIFT_WINDOW_NEXT_WORKSPACE,
	SHIFT_WINDOW_PREVIOUS_WORKSPACE,

	TOGGLE_FLOATING_WINDOW,

	EXEC,

	FOCUS_WORKSPACE_1,
	FOCUS_WORKSPACE_2,
	FOCUS_WORKSPACE_3,
	FOCUS_WORKSPACE_4,
	FOCUS_WORKSPACE_5,
	FOCUS_WORKSPACE_6,
	FOCUS_WORKSPACE_7,
	FOCUS_WORKSPACE_8,
	FOCUS_WORKSPACE_9,

	RESTART,
	UPDATE,
}
